# Generated by Django 3.0.3 on 2020-07-26 20:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('stock_available', models.IntegerField()),
                ('landing_cost', models.DecimalField(decimal_places=2, max_digits=55)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='SalesRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField()),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=55)),
                ('sold_date', models.DateField(default=django.utils.timezone.localdate)),
                ('item_profit', models.DecimalField(decimal_places=2, default=0, max_digits=55)),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sstock', to='stocks_ubm.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField()),
                ('purchased_date', models.DateField(default=django.utils.timezone.localdate)),
                ('updated_landing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=55)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_ubm.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=55)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=55)),
                ('discount', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_ubm.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=55)),
                ('discount', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=55)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_ubm.Stock')),
            ],
        ),
    ]
