# Generated by Django 3.0.3 on 2020-07-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['product_name']},
        ),
        migrations.AlterField(
            model_name='stock',
            name='landing_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=20000),
        ),
    ]
