# Generated by Django 3.0.3 on 2020-07-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0002_auto_20200715_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='profit',
            field=models.FloatField(default=1.15),
        ),
    ]
