# Generated by Django 3.0.3 on 2020-07-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0003_stock_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='profit',
            field=models.DecimalField(decimal_places=0, default=1.15, max_digits=20000, null=True),
        ),
    ]
