# Generated by Django 3.0.3 on 2020-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0004_auto_20200715_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='stock',
            name='profit',
            field=models.DecimalField(decimal_places=0, default=1.15, max_digits=20000),
        ),
    ]
