# Generated by Django 3.0.3 on 2020-07-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0005_auto_20200715_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=1.15, max_digits=10),
        ),
    ]
