# Generated by Django 3.0.3 on 2020-07-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0006_auto_20200715_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='selling_price',
        ),
    ]
