# Generated by Django 3.0.3 on 2020-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0007_auto_20200715_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='landing_cost',
            field=models.FloatField(),
        ),
    ]
