# Generated by Django 3.0.3 on 2020-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0008_auto_20200715_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='landing_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
