# Generated by Django 3.0.3 on 2020-07-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0010_auto_20200715_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
