# Generated by Django 3.0.3 on 2020-07-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0011_auto_20200715_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
