# Generated by Django 3.0.3 on 2020-07-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0013_auto_20200715_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='landing_cost',
            field=models.DecimalField(decimal_places=2, max_digits=55),
        ),
        migrations.CreateModel(
            name='SalesRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField()),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=55)),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_ubm.Stock')),
            ],
        ),
    ]
