# Generated by Django 3.0.3 on 2020-07-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0014_auto_20200717_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField()),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=55)),
                ('landing_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landingcost', to='stocks_ubm.Stock')),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productname', to='stocks_ubm.Stock')),
            ],
        ),
        migrations.DeleteModel(
            name='SalesRegister',
        ),
    ]
