# Generated by Django 3.0.3 on 2020-07-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0015_auto_20200717_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesregistry',
            name='landing_cost',
        ),
    ]
