# Generated by Django 3.0.3 on 2020-07-18 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0017_salesregistry_sold_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesregistry',
            name='stock_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_ubm.Stock'),
        ),
        migrations.CreateModel(
            name='PurchaseRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField()),
                ('purchased_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_landing_cost', models.DecimalField(decimal_places=2, max_digits=55)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_ubm.Stock')),
            ],
        ),
    ]
