# Generated by Django 3.0.3 on 2020-07-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0018_auto_20200718_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseregistry',
            name='updated_landing_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=55),
        ),
        migrations.AlterField(
            model_name='salesregistry',
            name='num_of_items',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesregistry',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=55),
        ),
        migrations.AlterField(
            model_name='salesregistry',
            name='stock_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stocks_ubm.Stock'),
        ),
    ]
