# Generated by Django 3.0.3 on 2020-07-22 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0019_auto_20200718_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesregistry',
            name='item_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=55),
        ),
        migrations.AlterField(
            model_name='salesregistry',
            name='num_of_items',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesregistry',
            name='sold_price',
            field=models.DecimalField(decimal_places=2, max_digits=55),
        ),
        migrations.AlterField(
            model_name='salesregistry',
            name='stock_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sstock', to='stocks_ubm.Stock'),
        ),
    ]
