# Generated by Django 3.0.3 on 2020-07-23 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0020_auto_20200722_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseregistry',
            name='purchased_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 23, 21, 3, 1, 601296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salesregistry',
            name='sold_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 23, 21, 3, 1, 600299, tzinfo=utc)),
        ),
    ]
