# Generated by Django 3.0.3 on 2020-07-23 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0021_auto_20200724_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseregistry',
            name='purchased_date',
            field=models.DateField(default=datetime.date(2020, 7, 23)),
        ),
        migrations.AlterField(
            model_name='salesregistry',
            name='sold_date',
            field=models.DateField(default=datetime.date(2020, 7, 23)),
        ),
    ]
