# Generated by Django 3.0.3 on 2020-07-23 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0024_auto_20200724_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseregistry',
            name='purchased_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='salesregistry',
            name='sold_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
