# Generated by Django 3.0.3 on 2020-07-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0025_auto_20200724_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('sold_price', models.IntegerField()),
                ('profit_gen', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_ubm.Stock')),
            ],
        ),
    ]
