# Generated by Django 3.0.3 on 2020-07-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0026_profitgen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfitGen',
        ),
    ]
