# Generated by Django 3.0.3 on 2020-07-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0027_delete_profitgen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=55)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=55)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_ubm.Stock')),
            ],
        ),
    ]
