# Generated by Django 3.0.3 on 2020-07-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0028_profitgen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitgen',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=55),
        ),
    ]
