# Generated by Django 3.0.3 on 2020-07-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_ubm', '0030_profitgen_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=55)),
                ('discount', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=55)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_ubm.Stock')),
            ],
        ),
    ]
